services:

    awd-vo-date-time-php-fpm:
        container_name: "awd-vo-date-time-php-fpm"
        build:
            context: ./docker/php-fpm
            args:
                PHP_VERSION: ${PHP_VERSION}
                uid: ${UID-1000}
                gid: ${GID-1000}
        volumes:
            - ${APP_ROOT_DIR}:${APP_CONTAINER_DIR}
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/conf.d:/usr/local/etc/php/conf.d
